### ISSUE TITLE
R12: Add a 'unit_of_measurement' attribute on appropriate technical metadata fields.

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#14]
Management of 'fps', 'ips' and 'rpm' per frame rate, 'kilobits/sec', 'megabits/sec' for data rate, etc. Allowing more technical fields to focus on machine-readable expression of numbers or equations rather than extra text expressions.  //  (Consider audio catalog resist using a field called framerate for ips and rpm data, consider renaming or moving.)

**Comment by pdpinch** [comment]
Considering adding a "units" or similar attribute to appropriate elements.

**Comment by pdpinch** [comment]
3fcbe9d4de685c36301d3e1ab86c99b12ae06773 has a new string type, technicalStringType which has an attribute unitsOfMeasure. Elements formatDataRate and essenceTrackDataRate are of type technicalStringType

Do we need a CV for unitsOfMeasure ?

**Comment by WeAreAVP** [comment]
OK I see the new technicalStringType, so far it's just on the formatDataRate and essenceTrackDataRate element, which is probably where it was most needed. FrameRate (ips, fps, rpm) could use something like this too. It's looks like sampllingRate and fileSize have unitsOfMeasure as part of the definition so probably not needed here.

I think CV's are needed here since concepts like 'kilobytes per second' may likely be expressed in a different way by each user.

**Comment by kvanmalssen** [comment]
I can see technicalStringType being useful in other places, like formatFileSize (MB, KB, GB), and essenceTrackFrameRate as Dave mentioned.  

CVs would be useful to control the entry, but might be confusing or limiting if unitsOfMeasure is available to other elements.

**Comment by MarcosSueiro** [comment]
In order to reduce the number of fields (and consolidate the analog and digital worlds), would it make sense to have just one repeatable playbackRate or encodingRate field, with attributes playbackRateType (frame rate, playback speed, sampling rate, etc) and unitsOfmeasure (with suggested vocab Hz, IPS, kbps)? 
As for the units CV, IASA recommends ISO, but I know this is a touchy subject in North America ;-)
