### ISSUE TITLE
R20: Recommend ISO 639-3

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#23]
Include ISO 639-3 (new since PBCore language documentation was written) as an additonal recommendation for language authority.

**Comment by pdpinch** [comment]
Note that with 5d0e20eabf4a35d9968d4d525d95f85f26990c45 3 letter language codes are now supported.

**Comment by WeAreAVP** [comment]
I wrote some XSL for the PBCore 2.0 RC and still say that the unique approach to language-handling with semicolon delimiters is very awkward. I have a system that needs to receive pbcore with multiple language expressions per instantiation and parse the values into a faceted browsing and this continues to be a big stumbling block. Keeping everyone aware that parsing the 'language' element requires a specialized approach just makes this more confusing. Is there any reason <i>why</i> PBCore adopted this policy:

"If the media item has more than one language that is considered part of the same primary audio or text, then a combination statement can be crafted, e.g., eng;fre for the presence of both English and French in the primary audio. Separating three-letter language codes with a semi-colon (no additional spaces) is preferred."

rather than simply giving language a maxOccurs="unbounded"? It's hard to imagine an advantage to concatenating the expressions like this in an XML environment.

**Comment by pdpinch** [comment]
Sorry Dave. We look forward to addressing this in PBCore 3.0. Maybe even 2.1.
