### ISSUE TITLE
R25: Allow classification of rightsSummary statements

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#28]
The utility of rightsSummary could be greatly expanded by providing a rightsType field and including the source and version attribute on the rights element. Potential rightsType could include: Permission Statement, Constraints, Obligations on Use, Access Permission, Indemnification Statement.

**Comment by pdpinch** [comment]
With the introduction of rightsType and rightsEmbedded in 5d0e20eabf4a35d9968d4d525d95f85f26990c45 this is now a documentation issue.

**Comment by MarcosSueiro** [comment]
There may also be an argument for having a rights field in the instantiation section (e.g., a photograph used in a documentary).

**Comment by jackbrighton** [comment]
Yes! Which is why I'm very happy about the new instantiationRights element. This will help clarify that (e.g.) the rights to download and reuse an mp4 file are different from the rights to access the original 10-bit uncompressed source video file. And many other cases where the rightsSummary for different instantiations would be different.

**Comment by pdpinch** [comment]
rightsSummary has attributes source, ref and version which can be used for this purpose.
