### ISSUE TITLE
R1b: For creator, contributor, and publisher provide support for management of (b) character portrayal (contributor only?),

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#3]
b. PBCore does not specifically address character portrayal in the contributor elements. For instance for a Sesame Street segment, PBCore can state <pbcoreContributor><contributor>Henson, Jim</contributor><contributorRole>Actor</contributorRole></pbcoreContributor> but does not provide a specific means to clarify whether Jim Henson is portraying Ernie or Kermit.

**Comment by pdpinch** [comment]
b. since this is use case is limited to a particular value of contributorType, it is difficult to come up with a widely applicable solution. Recommendation now is for PBCore authors to use annotation attribute. We will provide normative examples in the documentation.

**Comment by WeAreAVP** [comment]
I agree that it's a contributorType-specific issue, though using contributor@annotation only states that there is some annotation associated with the contributor and not that the data is a 'portrayal'. There is no way to trust that the annotation data is a 'portrayal' or not. Looking forward to panel comments here. Easiest solution may be to add a contributorPortrayal element (maxOccurs=unbounded).

**Comment by pdpinch** [comment]
Seems like a rabbit-hole to me, for what's otherwise a limited case. But making it a separate element keeps things clear and, perhaps, calling it contributorPortrayal will avoid the confusion over contributorRole.

**Comment by jackbrighton** [comment]
I agree adding contributorPortrayal is a good solution with minOccurs=0. While "portrayal" information isn't needed in nonfiction content, it's really important metadata for anything involving actors which is lots of content.

**Comment by WeAreAVP** [comment]
Hey Jack, in the 20101130 version of the schema 'portrayal' is added as an attribute (attributes are optional by default) to contributorRole (as one contributor may play multiple roles each with its own portrayal). Thus now:

&lt;pbcoreContributor&gt;

  &lt;contributor&gt;Hensen, Jim&lt;/contributor&gt;

  &lt;contributorRole&gt;Writer&lt;/contributorRole&gt;

  &lt;contributorRole portrayal="Kermit"&gt;Actor&lt;/contributorRole&gt;

  &lt;contributorRole portrayal="Ernie"&gt;Actor&lt;/contributorRole&gt;

&lt;/pbcoreContributor&gt;

is possible rather than listed multiple pbcoreContributors to reflect many roles.

I also found that now contributorRole is minOccurs="1" and thus now mandatory, which is anew development from 1.3. Any thoughts here? I know there have been many times while cataloging or mapping that I've known someone is a contributor but don't know the role. This adds a new requirement in that now at least one role MUST be declared in order to express a contributor.

**Comment by jackbrighton** [comment]
Good on the inclusion of the portrayal attribute. Would making this it's own element <contributorPortrayal> make it any easier to parse? 

On the issue of contributorRole being mandatory, it seems trivial to make it not. Otherwise if you don't know, you're stuck saying unknown.

**Comment by WeAreAVP** [comment]
Let me test:

&lt;xsl:value-of select="/pbcoreDocumentDescription/pbcoreContributor/contributorRole@portrayal"/&gt;

Result: I didn't break a sweat reaching for the "@" rather than the "/". Making it an element would actually make things more complicated since you'd need something like:

&lt;pbcoreContributor&gt;

&lt;contributor&gt;Hensen, Jim&lt;/contributor&gt;

&lt;pbcoreContributorRole&gt;

&lt;contributorRole&gt;Actor&lt;/contributorRole&gt;

&lt;portrayal&gt;Actor&lt;/portrayal&gt;

&lt;/pbcoreContributorRole&gt;

&lt;/pbcoreContributor&gt;

unless it was determined that 'portrayal' describes something other than the 'role'.

**Comment by WeAreAVP** [comment]
is this issue closed?

**Comment by jackbrighton** [comment]
I'd be very happy with it! And <portrayal> would be optional of course.

**Comment by jackbrighton** [comment]
P.S. This solves an issue I've heard multiple people complain about, especially (but not exclusively) film archivists.

**Comment by pdpinch** [comment]
There is now an attribute on contributorRole for portryal
