### ISSUE TITLE
Remove genreAuthorityUsed in favor of genre @source attribute ?

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#34]
Dave Rice said: 

> I'm still a little confused about the semantic difference between genreAuthorityUsed and the new source attribute on the genre element. Can you give an example.

and then later suggested:

> I don't think that removing one element and bringing in an attribute with the same semantic meaning will additionally hurt backwards compatibility.

**Comment by WeAreAVP** [comment]
I'd add that this issue also affect pbcoreIdentifier/identifier@source vs pbcoreIdentiifer/identifierSource and subjectAuthorityUsed and partly relationIdentifier.

**Comment by dmaccarn** [comment]
Just a reminder that @source was added in 1.3, so a not a new issue specific to 2.0

**Comment by kvanmalssen** [comment]
I'm also confused by this.

**Comment by dmaccarn** [comment]
Both elements genre and genreAuthorityUsed have the string type sourceVersionString which includes the optional @source.  In the case of the element genre the @source would be redundant to the reference in the element genreAuthorityUsed.  This was not intentional but could be confusing.  We could make the genre string type just string or make up a new type but the idea was just to use the one that was already available.

**Comment by WeAreAVP** [comment]
Without any documentation or samples on the sourceVersionString type, this is hard to evaluate. I presume that the source attribute for genreAuthorityUsed expresses the source of what is expressed in genreAuthorityUsed, but I'm not sure why. Would this be &lt;genreAuthorityUsed source="WGBH"&gt;PBCore Genre List&lt;/genreAuthorityUsed&gt;? Because WGBH was the source organization for the "PBCore Genre List"? Would the source attribute for genre then also be "PBCore Genre List"? This is a bit meta-meta.

**Comment by dmaccarn** [comment]
As I said we could make the genre string type just string or make up a new type.

**Comment by dmaccarn** [comment]
I'm liking the idea of removing genreAthorityUsed in keeping the attributes @source @version @ annotation.
