### ISSUE TITLE
R3: Allow management of dates and types of dates that pertain to the intellectual content of the asset (beyond coverage_spatial).

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#6]
"For example, the film “Gone With the Wind” was released in 1936. If cataloging a VHS instantiation of the film then dateCreated refers to the VHS tape's release. PBCore should provide a specific method to store dates affiliated with the intellectual content (i.e. to say that GWTW was release in 1936).

Additionally documentation on dateCreated and dateIssued should be clarified. Often users will store dateCreated and dateIssued values that do not pertain to the instantiation or even occur before the technical format listed in formatDigital or formatPhysical even existed (due to using the instantiation-specific date fields to manage asset-specific date information)."

**Comment by pdpinch** [comment]
We plan to change the dateCreated element in the pbcoreInstantiation container to be "instantiationDateCreated"

We will add a dateCreated element to the intellectual content section (within the PBCoreDescriptionDocument container).

**Comment by WeAreAVP** [comment]
This revision only allows for the description of one type of date in relation to the asset, which is dateCreated. For instance a common identified value to express is the date of original broadcast which is not easily expressible in this draft. Additionally in PBCore 1.3's value pbcoreAssetType is not required; however in PBCore 2.0 if the new dateCreated field is used then an assetType (2.0 draft 3 appears to have replaced pbcoreAssetType with pbcoreAssetType/assetType) is also required. Since dateCreated and assetType have little to do with one another the use of one should not require the use of the other.

**Comment by WeAreAVP** [comment]
Can we consider an EBUCore style approach in PBCore such as have a 'pbcoreDate' element within the 'pbcoreDocumentDescriptionType' complexType? Such as:

<xsd:element maxOccurs="unbounded" minOccurs="1" name="pbcoreDate">
   xsd:complexType
      xsd:sequence
         <xsd:element maxOccurs="1" minOccurs="1" name="date" type="xsd:string"/>
         <xsd:element maxOccurs="1" minOccurs="0" name="dateType" type="sourceVersionStringType"/>
      /xsd:sequence
   /xsd:complexType
/xsd:element

**Comment by dmaccarn** [comment]
Isn't that what the instantiation dates are for? dateavailable etc.

**Comment by WeAreAVP** [comment]
This request is particular to expressing dates about the asset. For instance say you have a CD recording made in 2005 of a radio broadcast that was initially created in 1965 and broadcast in 1966. In PBCore for the instantiation of the CD you can say that the dateIssued is 2005 (probably no known instantiation/dateCreated in this case), but there is no where to express the two dates (broadcast and creation) of asset. This caused a lot of problems in the pilot project and some folks would say that instantiation/dateCreated was 1965 and formatPhysical was a Betacam, which is not possible.

**Comment by dmaccarn** [comment]
In your example, wouldn't the created date be the new element assetType/dateCreated and then the CD was created and has instantiationDateCreated and then a broadcast date would be dateAvailable?

**Comment by WeAreAVP** [comment]
Yes in this case. But then the user must enter assetType/assetType whereas the use of assetType/assetType is optional for those not using dateCreated. I'm not sure why the elements are set up so that if one is optionally used then the other must be used.

Also this doesn't address other kinds of intellectual dates. For instance Andy Lanset has CDs of radio broadcasts from the 1950 where he knows the original date of broadcast, but there is no where to store it. The CD itself was not dateIssued in the 1950s.

**Comment by WeAreAVP** [comment]
Also the requirements go the other way. Now in 2.0 draft 3, the user can't say assetType/assetType unless they also state the assetType/dateCreated.

**Comment by pdpinch** [comment]
> For instance Andy Lanset has CDs of radio broadcasts from the 1950 where he knows the original date of broadcast

Re: broadcast date. The proposal is to recommend using dateAvailable to indicate original broadcast dates. Would you recommend a different approach?

(I'm also contemplating breaking this into a separate issue for tracking purposes)

**Comment by dmaccarn** [comment]
First, your are talking about pbcoreAssetType/assetType right?
If you have a pbcoreAssetType then you must have a pbcoreAssetType/assetType and a pbcoreAssetType/datedCreated.
Isn't there an instantiation if there is a radio broadcast that has a recording?

**Comment by WeAreAVP** [comment]
dateAvailable refers specifically to the instantiation and not the intellectual content of the asset. In this case the CD could not possibly be available in 1950 because it did not physically exist. Since this issue is specifically about dates that refer to the asset (not the instantiation) I'd recommend following examples of Dublin Core and EBU Core and adding a date/dateType element.

**Comment by WeAreAVP** [comment]
Looking at the 20101130 version. The new date element and dateStringType look great, but the position in the XSD still means that the assetType element must be used in order to use date. This dependency seems unrelated. Could the date element just be moved up a level and out of the pbcoreAssetType element?

**Comment by dmaccarn** [comment]
I'll make a note, though I don't see why one wouldn't use the assetType with the date.

**Comment by WeAreAVP** [comment]
I picturing training a cataloger who enters a date and trying to explain that even though pbcoreAssetType is optional, now they either have to enter assetType or lose the date. The connection doesn't seem obvious to me.

**Comment by WeAreAVP** [comment]
In response to "I don't see why one wouldn't use the assetType with the date", I don't understand why date is getting called out to fulfill extra pre-requisites before use. For instance, a user can express coverage(Temporal) without expressing the assetType, why is 'date' under a different set of requirements.

In working on a media inventory at the UN, I see massive percentages of the collection are tapes that include a 'date' that defines the intellectual content but contain no easy indication of what the asset type is (could be an interview, an episode, broll, etc). This unrelated requirement is going to mean that users may have to guess an assetType when they would not otherwise state it just to be allowed to say the date, or else we need to go back to using Dublin Core in the PBCore extension element to express dates.

**Comment by dmaccarn** [comment]
Roger, will look at this.

**Comment by MarcosSueiro** [comment]
Greetings - 

I agree with Dave that linking date with assetType seems awkward. Our proposal would be to have the assetDate field unbounded and with minOccur=0, with an assetDateType which suggests (but does not limit it to) a restricted vocab (e.g. broadcast, created, edited, found, entered, donated). Also, strongly suggest using ISO 8601 extended date formatting YYYY-MM-DD or YYYY-MM-DDThh:mm:ss, with "xx" or "uu" for unknown (and allow for start-end formatting, as in "2007-03-01T13:00:00Z/2008-05-11T15:30:00Z"). And repeat the exact same setup for instantiationDate.
http://www.iso.org/iso/date_and_time_format

Our dates can get pretty complicated and this would allow us maximum flexibility. We also feel that ISO 8601 is not that difficult to grasp (but why does it not have a provision for unknown fields??)

**Comment by WeAreAVP** [comment]
I agree and ISO 8601 is already the recommendation of at least a few of the date fields (maybe all), but there will still be many folks entering in awkwardly formatted date expressions, so currently date fields are text strings but the recommendation is ISO 8601. Change the date element to follow an ISO 8601 regular expression would mean that everyone would have to use it (lots of benefits to that, but I suppose it could be hard or frustrating to many). 

Marcos' reference to using a date/dateType approach with instantiation as well is interesting. Potentially instantiation/dateCreated would then be instantiation/date where type="Created". I suppose the advantages here are that you could use other type of dates in association with an instantiation beyond the two provided. Also multiple dates of any type could be expressed whereas both dateCreated and dateIssued can only happen zero or one times per instantiation.

**Comment by dmaccarn** [comment]
pbcoreAssetType and pbcoreAssetDate are no longer tied together.
Also instantiationDate now has a dateType and can fill the roll of instantiationCreated, dateIssued, dateAvailableStart and End.  This will have to be added to the CV list.

**Comment by WeAreAVP** [comment]
Among the vocab group I emailed earlier today that we need to think about dateType, I suppose now in both relation to assets and instantiations. I think dateAvailableStart/End is the one set of PBCore fields I've never used but can the date/dateType structure in the instantiation element provide the relationship between start and end; for instance to say the item is available from Monday through Tuesday then again from Thursday through Friday. On the other hand, as Marcos pointed out, ISO 8601 already provides a standardized way to express ranges with the "/" delimiter.

**Comment by MarcosSueiro** [comment]
I would also not enforce using ISO 8601, but it is the most potentially parseable standard down the road. As an example, I believe 

to say the item is available from Monday through Tuesday then again from Thursday through Friday

would require two date fields with dateType="available" of

xxxx-Wxx-1/xxxx-Wxx-2
xxxx-Wxx-4/xxxx-Wxx-5

(again, as long as x's (LC uses uu) are kosher within ISO --anybody know?) Not exactly very person-friendly, but consistent.
