### ISSUE TITLE
R4: Provide recommendations to identify/describe asset types that do not conform to the typical TV-Guide-style genre lists (such as pre-production classifications of content such as interview, broll, stock footage, sot, outtakes, etc)

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#7]
More attention is needed within controlled vocabularies and documentation in regards to non-broadcast media material in order to increase relevance of PBCore to earlier stages of media workflow.

**Comment by pdpinch** [comment]
In PBCore 1.3 we added an assetType element to address this issue. The new element needs to be documented, and it's controlled vocabulary needs to be formalized.

**Comment by WeAreAVP** [comment]
assetType for this info sounds good, though I think the max and minoccurs of this element and its parent element need to be reviewed.

**Comment by jackbrighton** [comment]
I like where assetType is going here. But I'm dubious that any controlled vocabulary we provide will cover all assetTypes for all potential users, nor should it. This would be another good place to allow schema-based profiles. Documentation should also make clear the difference between assetType and titleType where the taxonomy also includes program and clip. BTW, the draft XSD and the PDF version both have a typo in the documentation where they refer to this first as "assetKind".

**Comment by WeAreAVP** [comment]
In interest of time, can we close this item? The latest draft still contains references to 'assetKind' but I feel there are other outstanding priorities.

**Comment by MarcosSueiro** [comment]
I hate to say this, because at first it seemed like a good idea, but I do not see the use of assetType, esp if its entries are going to be very close to titleType. Seems like assetType is what the asset _is_, while titleType is what you are _calling it_. A subtle difference in practical terms. Am I missing something?

**Comment by WeAreAVP** [comment]
titleType defines the title and not the asset directly. For instance you're asset may have many titles with the titletypes such as "Alternate", "Working", "Marketing" and "Episode". The asset itself isn't "Alternate" or "Working", it just happens to have titles that are. In this case saying assetType="Episode" makes the overall context of the asset more clear.

**Comment by MarcosSueiro** [comment]
Understood. Should then there be a mandatory title whose titleType=assetType?

**Comment by WeAreAVP** [comment]
I suppose that's recommended in some cases, but assetType has scope for more informal material as well (right?). For instance assetType="Interview" or assetType="B-Roll", the title might not even have a titleType in cases like that.

**Comment by MarcosSueiro** [comment]
Come to think of it, I would vote to make "asset" a titleType, so that it can be quite free and uncontrolled. You can then enter in the title "B Roll" or "Interview" or whatever --or both. 

Although I understand the reasoning, I keep finding dangerous having an (optional) element where you state what the asset _is_ (not what you _call it_), but not have any CV. As Dave says, you could then define one asset as "interview" and another as "B-roll" --in my mind, quite different attributes.

But I guess we are free not to use it ;-)

**Comment by WeAreAVP** [comment]
My preference is that titleType ONLY be used to say what kind of title is associated with it. Having titleType like "B Roll" doesn't really make sense to me. (?) assetType seems more appropriate.

**Comment by MarcosSueiro** [comment]
Sorry, I did not explain this clearly. I am suggesting entering (say) "B-roll" as a (free-text) title, with titleType=asset.

**Comment by pdpinch** [comment]
There is a recommended CV for assetType, and then new field is in the documentation.

I'm closing this issue.
